name: Lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.9.3"
          enable-cache: true
          cache-dependency-glob: "**/requirements*.txt"

      - name: Cache Home Assistant installation
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            .local/ha-venv
          key: ha-venv-${{ runner.os }}-py313-lint-${{ hashFiles('requirements_dev.txt') }}
          restore-keys: |
            ha-venv-${{ runner.os }}-py313-lint-

      - name: Install lint dependencies
        run: |
          if [ ! -d .local/ha-venv ]; then
            uv venv .local/ha-venv
          fi
          source .local/ha-venv/bin/activate
          uv pip install --upgrade --requirement requirements_dev.txt
          uv pip install --upgrade ruff

      - name: Lint check
        run: script/lint-check
